MODEL:  
  TEMPERATURE: 
  STREAM: True

  SERVICE: # [ ollama, openai, groq, gemini ] 

  EMBEDDING_MODEL_NAME: 
  EMBEDDING_SERVICE: # [ollama, openai, hf]

  MODEL_ID:

  VECTOR_STORE: # currently support [qdrant, chroma] 
